//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public int CityID { get; set; }
        public double city_latitude { get; set; }
        public double city_longitude { get; set; }
        public string city_name { get; set; }
        public string city_description { get; set; }
    }
}
